### ISSUE TITLE
RTAN - onVehicleKilled

### ISSUE THREAD

**Issue by elektrosmoker** [Aimdrol/MLG-RTAN#1]
[python.log](https://github.com/Aimdrol/MLG-RTAN/files/3636821/python.log)
hy there,

i´m from Relhax and we got some bug reports concerning the rtan mod of yours.
thats why we wanted to inform you about that.

thx in advance 
-elektro-

here´s an extract of the python.log:

`2019-09-20 13:50:28.922: INFO: [SOUND] Event 2641540682 . Error The ID was not found
2019-09-20 13:50:32.162: INFO: [SOUND] Event 326256530 . Error The ID was not found
2019-09-20 13:50:33.895: ERROR: Traceback (most recent call last):
2019-09-20 13:50:33.895: ERROR:   File "scripts/client/Avatar.py", line 2279, in updateArena
2019-09-20 13:50:33.895: ERROR:   File "scripts/client_common/ClientArena.py", line 288, in update
2019-09-20 13:50:33.895: ERROR:   File "python\gui\pmod\utils.py", line 18, in <lambda>
2019-09-20 13:50:33.896: ERROR:   File "_legacy", line 1, in hooked_onVehicleKilled
2019-09-20 13:50:33.896: ERROR:   File "mod_RTAN.py", line 57, in new_onVehicleKilled
2019-09-20 13:50:33.896: ERROR: ValueError: need more than 4 values to unpack`

**Comment by Aimdrol** [comment]
Fixed with a46fcb7c34a3b19e21331b40dfe675ec272d154d
